### PR TITLE
Update to use hiredis v0.12.0

### LINKED ISSUE #75: Upgrade to Hiredis 0.12.0
https://github.com/redis/hiredis/blob/master/CHANGELOG.md

### PR DESCRIPTION
**Pull request by badboy**
This bundles the PRs #67 and #71, #66  
It closes #75, #73 

/cc @pietern. I think we should bundle this up and push it to NPM. I'll add another commit to bump the version number.

### CODE REVIEW

**Comment by prabhu** [comment]
+1 for the merge

**Comment by zj8487** [comment]
+1

**Comment by ilkkao** [comment]
I think nan bump should be merged separately if this PR is not ready to go out. Nan upgrade is trivial and makes hiredis usable with io.js.

**Comment by badboy** [comment]
It absolutely is. Just hadn't the time to get it out, but it's planned for today

**Comment by ilkkao** [comment]
Great! I'm just eager to use hiredis with io.js :)

**Comment by beeant** [comment]
+1

**Comment by AntouanK** [comment]
+1

**Comment by badboy** [comment]
– Looks like we're good to go.

**Comment by AntouanK** [comment]
:tada:

**Comment by badboy** [comment]
yeah, all that's missing now is the ability to push to npm, but @pietern is informed

**Comment by AntouanK** [comment]
@badboy Is hiredis-node ready for io.js? I get this error on 1.4.2
```bash
➜  hnadmin git:(redesign) ✗ npm i hiredis

> hiredis@0.2.0 install /Users/antouank/_REPOS_/node_modules/hiredis
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:403:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:293:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/antouank/_REPOS_/node_modules/hiredis
gyp ERR! node -v v1.4.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "hiredis"
npm ERR! node v1.4.2
npm ERR! npm  v2.6.1
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/antouank/_REPOS_/hnadmin/npm-debug.log
```

**Comment by badboy** [comment]
Builds fine for me.

```
gyp ERR! stack Error: 404 status code downloading tarball
```

Somehow it couldn't download the tarball. I just tried and it works fine. Maybe some problems with your network, a proxy or even the npm repository?
Does this error occur everytime?

**Comment by AntouanK** [comment]
I thought the same.
But other packages install just fine.
I get the same 404 code, yes.

**Comment by badboy** [comment]
Looks like there are issues with node-gyp and io.js. May be relevant: https://github.com/iojs/io.js/issues/433, though that should be fixed by now.

**Comment by AntouanK** [comment]
Maybe.

I tried `node-sass` ( I know it also uses node-gyp ) and I get an error, which I think refers to the same thing.

```bash

> node-sass@2.0.1 install /Users/antouank/_REPOS_/hnadmin/mirror-db/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-iojs-1.4/binding.node

> node-sass@2.0.1 postinstall /Users/antouank/_REPOS_/hnadmin/mirror-db/node_modules/node-sass
> node scripts/build.js

module.js:322
    throw err;
          ^
Error: Cannot find module '/Users/antouank/_REPOS_/hnadmin/mirror-db/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:112:16)
    at node.js:863:3
Build failed
```

**Comment by AntouanK** [comment]
@badboy What's the manual way of getting the hiredis package?
Clone the repo in `node_modules`?

**Comment by badboy** [comment]
@AntouanK Yep, that should work.

**Pull request closed without merging**
