### PR TITLE
upgrade nan

### PR DESCRIPTION
**Pull request by heavyk**
bump nan for iojs-2.0.0 compat
(I used the ^ so a republish isn't needed every release. see: https://github.com/iojs/io.js/issues/1620)

### CODE REVIEW

**Comment by badboy** [comment]
This fails for node 0.8 which still uses an old npm.
But if I just upgrade to the latest version, something else fails: https://travis-ci.org/redis/hiredis-node/jobs/61416531

**Comment by dpatti** [comment]
I've had this problem too, and I fixed it by changing my travis file to this:

```yaml
install:
  - npm update -g npm
  - npm install
```

Example: https://github.com/trello/node-coffee-cache/blob/2.x/.travis.yml#L6-L8

**Comment by dpatti** [comment]
Sorry, deleted my last comment because that was just me clicking the wrong link. As for your `pr-84` branch, I can build that successfully locally, and the error makes it look like a travis problem. Did you try re-running it?

**Comment by heavyk** [comment]
that error is a bug in node-gyp. I mentioned how to fix it last night here...
https://github.com/audreyt/node-webworker-threads/issues/55#event-298315265
I don't know much about travis, but you have to link the node-gyp that comes with iojs for that to work. (I had to change a few docker containers to do exactly that)

**Comment by badboy** [comment]
Yay! ¬_¬ I see what I can do

**Comment by heavyk** [comment]
pr-84 branch works perfect, thanks

**Comment by badboy** [comment]
I finally pulled this in, thanks!

**Comment by heavyk** [comment]
nice, even with the `^` and everything :)

**Pull request closed without merging**
