### PR TITLE
:arrow_up: nan@~1.5.0 for iojs support

### PR DESCRIPTION
**Pull request by jonathanong**

### CODE REVIEW

**Comment by timoxley** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by salzhrani** [comment]
+1

**Comment by zj8487** [comment]
+1

**Comment by salzhrani** [comment]
Maybe @michael-grunder or @pietern could help

**Comment by indutny** [comment]
@antirez ping ;)

**Comment by badboy** [comment]
I'll take care of it the next week

**Comment by indutny** [comment]
Thanks!

**Pull request closed without merging**
